"""add actor identifier to audit logs

Revision ID: 080e979efeb1
Revises: 68c2452a5d4e
Create Date: 2026-05-09 10:34:00.328149

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080e979efeb1'
down_revision: Union[str, Sequence[str], None] = '68c2452a5d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_identifier_enc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'actor_identifier_enc')
    # ### end Alembic commands ###
