"""remove auto_generate fields

Revision ID: 0f4dfc7e562f
Revises: 2dec891da389
Create Date: 2026-06-15 18:12:00.903397

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f4dfc7e562f'
down_revision: Union[str, Sequence[str], None] = '2dec891da389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_concepts', 'auto_generate_time')
    op.drop_column('payment_concepts', 'auto_generate_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_concepts', sa.Column('auto_generate_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payment_concepts', sa.Column('auto_generate_time', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
