"""Add payments module models

Revision ID: 2dec891da389
Revises: 0006_push_tokens
Create Date: 2026-06-15 17:47:47.263616

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dec891da389'
down_revision: Union[str, Sequence[str], None] = '0006_push_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('auto_generate_day', sa.Integer(), nullable=True),
    sa.Column('auto_generate_time', sa.Time(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_concepts_name'), 'payment_concepts', ['name'], unique=False)
    op.create_index(op.f('ix_payment_concepts_school_id'), 'payment_concepts', ['school_id'], unique=False)
    op.create_index('uq_payment_concepts_school_name_active', 'payment_concepts', ['school_id', 'name'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('student_debts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='debtstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['payment_concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_debts_concept_id'), 'student_debts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_student_debts_student_id'), 'student_debts', ['student_id'], unique=False)
    op.create_table('student_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('student_debt_id', sa.Uuid(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_debt_id'], ['student_debts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_payments_student_debt_id'), 'student_payments', ['student_debt_id'], unique=False)
    op.create_index(op.f('ix_student_payments_transaction_id'), 'student_payments', ['transaction_id'], unique=False)
    op.drop_constraint(op.f('push_tokens_token_key'), 'push_tokens', type_='unique')
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=True)
    op.drop_index(op.f('ix_student_communication_student_created'), table_name='student_communication')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_communication_student_created'), 'student_communication', ['student_id', 'created_date'], unique=False)
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('push_tokens_token_key'), 'push_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_student_payments_transaction_id'), table_name='student_payments')
    op.drop_index(op.f('ix_student_payments_student_debt_id'), table_name='student_payments')
    op.drop_table('student_payments')
    op.drop_index(op.f('ix_student_debts_student_id'), table_name='student_debts')
    op.drop_index(op.f('ix_student_debts_concept_id'), table_name='student_debts')
    op.drop_table('student_debts')
    op.drop_index('uq_payment_concepts_school_name_active', table_name='payment_concepts', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_payment_concepts_school_id'), table_name='payment_concepts')
    op.drop_index(op.f('ix_payment_concepts_name'), table_name='payment_concepts')
    op.drop_table('payment_concepts')
    # ### end Alembic commands ###
