"""add report runs model

Revision ID: 4bb6966e19ee
Revises: 080e979efeb1
Create Date: 2026-05-11 18:20:55.929333

"""
import sqlalchemy as sa
from alembic import op
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '4bb6966e19ee'
down_revision: Union[str, Sequence[str], None] = '080e979efeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('ATTENDANCE', 'EVALUATION_GRADEBOOK', 'TERM_AVERAGE', name='reporttype'), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('columns_json', sa.JSON(), nullable=True),
    sa.Column('format', sa.Enum('XLSX', 'PDF', name='reportformat'), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_runs_report_type'), 'report_runs', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_runs_school_id'), 'report_runs', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_runs_school_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_report_type'), table_name='report_runs')
    op.drop_table('report_runs')
    # ### end Alembic commands ###
