"""cluster

Revision ID: 5dc3fe56a42c
Revises: 4bb6966e19ee
Create Date: 2026-05-11 19:25:46.652467

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc3fe56a42c'
down_revision: Union[str, Sequence[str], None] = '4bb6966e19ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_cluster_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('trained_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('features_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('k_value', sa.Integer(), nullable=False),
    sa.Column('inertia', sa.Float(), nullable=False),
    sa.Column('silhouette_score', sa.Float(), nullable=True),
    sa.Column('model_artifact_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['trained_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_cluster_runs_assignment_id'), 'student_cluster_runs', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_student_cluster_runs_is_active'), 'student_cluster_runs', ['is_active'], unique=False)
    op.create_index(op.f('ix_student_cluster_runs_school_id'), 'student_cluster_runs', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_cluster_runs_term_id'), 'student_cluster_runs', ['term_id'], unique=False)
    op.create_index(op.f('ix_student_cluster_runs_trained_by_user_id'), 'student_cluster_runs', ['trained_by_user_id'], unique=False)
    op.create_index('uq_student_cluster_runs_active_context', 'student_cluster_runs', ['school_id', 'assignment_id', 'term_id'], unique=True, sqlite_where=sa.text('state = 1 AND is_active = 1'), postgresql_where=sa.text('state = true AND is_active = true'))
    op.create_table('student_cluster_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('attendance_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['student_cluster_runs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_cluster_results_run_id'), 'student_cluster_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_student_cluster_results_school_id'), 'student_cluster_results', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_cluster_results_student_id'), 'student_cluster_results', ['student_id'], unique=False)
    op.create_index('uq_student_cluster_results_run_student_active', 'student_cluster_results', ['run_id', 'student_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_student_cluster_results_run_student_active', table_name='student_cluster_results', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_student_cluster_results_student_id'), table_name='student_cluster_results')
    op.drop_index(op.f('ix_student_cluster_results_school_id'), table_name='student_cluster_results')
    op.drop_index(op.f('ix_student_cluster_results_run_id'), table_name='student_cluster_results')
    op.drop_table('student_cluster_results')
    op.drop_index('uq_student_cluster_runs_active_context', table_name='student_cluster_runs', sqlite_where=sa.text('state = 1 AND is_active = 1'), postgresql_where=sa.text('state = true AND is_active = true'))
    op.drop_index(op.f('ix_student_cluster_runs_trained_by_user_id'), table_name='student_cluster_runs')
    op.drop_index(op.f('ix_student_cluster_runs_term_id'), table_name='student_cluster_runs')
    op.drop_index(op.f('ix_student_cluster_runs_school_id'), table_name='student_cluster_runs')
    op.drop_index(op.f('ix_student_cluster_runs_is_active'), table_name='student_cluster_runs')
    op.drop_index(op.f('ix_student_cluster_runs_assignment_id'), table_name='student_cluster_runs')
    op.drop_table('student_cluster_runs')
    # ### end Alembic commands ###
