"""add audit logs table

Revision ID: 68c2452a5d4e
Revises: fc2d0cc5cf69
Create Date: 2026-05-08 23:36:12.986212

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c2452a5d4e'
down_revision: Union[str, Sequence[str], None] = 'fc2d0cc5cf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Enum('SYSTEM', 'SCHOOL', name='auditscope'), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'REGISTER', 'CREATE', 'UPDATE', 'DELETE', 'ACCESS', 'INVITE', 'ROLE_CHANGE', name='auditaction'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='auditstatus'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('description_enc', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('ip_enc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_scope'), 'audit_logs', ['scope'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_scope'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
